version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_people
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'people'
      MYSQL_USER: 'upeople'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - ./people.sql:/docker-entrypoint-initdb.d/people.sql
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: php_apache_web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
